### ISSUE TITLE
Sometimes fails to communicate with mustard server

### ISSUE THREAD

**Issue by philipfalkner** [team-mustardd/MustardBot-discord#11]
Sent a `!mustard-day` command, and 2 minutes later got the response `There was an error trying to execute that command!`.

The error from the bot's heroku log was that it failed to parse a JSON response with an unexpected character `<`. Was the response in HTML...?

**Comment by philipfalkner** [comment]
Found the problem.

The bot is making a POST request on http. The Azure app is redirecting that to https for security. The bot follows the redirect but now uses a GET instead of POST. The server (correctly) responds with a message that verb is wrong.

Easy fix: Just use https from the start.

**Comment by katrinarenwick** [comment]
♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️
